config/routes.rb
FluApp::Application.routes.draw do  
  
 resources :symptom_sets
 
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  root to: 'static_pages#home'

  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/signup', to: 'users#new'
  
  get "users/new"

  

end

app/models/symptom.rb
class Symptom < ActiveRecord::Base
  attr_accessible :name, :duration
  belongs_to :symptom_set
end

app/models/symptom_set.rb
class SymptomSet < ActiveRecord::Base
  attr_accessible :symptoms, :symptoms_attributes
  belongs_to :user
  has_many :symptoms, :dependent => :destroy
  accepts_nested_attributes_for :symptoms, :reject_if => lambda { |a| a[:name].blank?}, :allow_destroy => true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password
  has_many :symptom_sets, dependent: :destroy

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true


  private
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
# Filters added to this controller apply to all controllers in the application.
# Likewise, all the methods added will be available for all controllers.

class ApplicationController < ActionController::Base
  include SessionsHelper
  helper :all # include all helpers, all the time

  protect_from_forgery # See ActionController::RequestForgeryProtection for details

  # Scrub sensitive parameters from your log
  # filter_parameter_logging :password
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/symptom_sets_controller.rb
class SymptomSetsController < ApplicationController
  before_filter :signed_in_user, only: [:create, :new]
  before_filter :correct_user, only: [:index, :show, :edit, :destroy, :update]


  
  def index
    user = User.find(params[:user_id])
    @symptom_sets = user.symptom_sets.find_by_user_id(params[:user_id])
  end

  def show
    user = User.find(params[:user_id])
    @symptom_set = user.SymptomSet.find(params[:id])
  end

  def new
    @symptom_set = SymptomSet.new
    3.times do
      symptom = @symptom_set.symptoms.build
    end
  end



   def create
    @symptom_set = current_user.symptom_sets.new(params[:symptom_set])
    if @symptom_set.save
      flash[:success] = "Symptoms submitted!"
      redirect_to root_url
    else
      render 'static_pages/home'
    end
  end

  def edit
    @symptom_set = SymptomSet.find(params[:id])
  end

  def update
    @symptom_set = SymptomSet.find(params[:id])
    if @symptom_set.update_attributes(params[:symptom_set])
      redirect_to @symptom_set, :notice  => "Successfully updated symptom set."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @symptom_set = SymptomSet.find(params[:id])
    @symptom_set.destroy
    redirect_to symptom_sets_url, :notice => "Successfully destroyed symptom set."
  end
  
  private

    def correct_user
      @symptom_set = current_user.symptom_sets.find_by_id(params[:id])
      redirect_to root_url if @symptom_set.nil?
    end
end

app/controllers/symptoms_controller.rb
class SymptomsController < ApplicationController
  
  def show
    @symptom = Symptom.find(params[:name])
  end
  
  def index
  end

  def new
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_filter :correct_user,   only: [:edit, :update]
  before_filter :admin_user,     only: :destroy
  
  def edit
  end

  def show
    @user = User.find(params[:id])
    @symptom_sets = @user.symptom_sets.paginate(page: params[:page])

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Flu App!"
      redirect_to @user
    else
      render 'new'
    end
  end


  def update
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end



  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end

 def index
    @users = User.paginate(page: params[:page])
  end

  private

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    @content_for_title = page_title.to_s
    @show_title = show_title
  end
  
  def show_title?
    @show_title
  end
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end
  
  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user?(user)
    user == current_user
  end

   def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/symptom_sets_helper.rb
module SymptomSetsHelper
end

app/helpers/symptom_submissions_helper.rb
module SymptomSubmissionsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://salathegroup.com/">Salathe Research Group</a>
    by Ells Campbell
  </small>
    <nav>
      <ul>
        <li><%= link_to "About",   about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <li><a href="http://blog.salathegroup.com/">Blog</a></li>
      </ul>
   </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Flu App", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flu App</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
        
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li> <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_interaction_trunk.html.erb
<h1>
  <span6>Welcome, </span><%= current_user.name %>
</h1>

<div class="navbar row-fluid">
  <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">I am...</a>
        <div class="nav-collapse">
          
          <ul class="nav">
          	<div class="btn-group row-fluid">
          	   <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                  Worried<span class="caret"></span></a>
                    <ul class="dropdown-menu">
               		    <a href="http://crowdbreaks.com">Crowdbreaks</a> 
               	      <a href="http://www.google.org/flutrends/">Google FluTrends</a> 
                    </ul>
            </div>
        </ul>
          
          <ul class="nav">
          	<div class="btn-group row-fluid">
          	   <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                  Sick<span class="caret"></span></a>
                    <ul class="dropdown-menu">
               		    <li><%= link_to "What do I have?", new_symptom_set_path %></li> 
                    </ul>
            </div>
        </ul>
          
          <ul class="nav">
          	<div class="btn-group row-fluid">
          	   <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                  Intrigued<span class="caret"></span></a>
                    <ul class="dropdown-menu">
               		    <a href="http://salathegroup.com">IP</a> 
               	      <a href="http://salathegroup.com">IP</a> 
                    </ul>
            </div>
        </ul>
      </div>
    </div>
  </div>
</div>
    





<span>
  <%= link_to "view my profile", current_user %>
</span>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>"><%= gravatar_for current_user %></a>

<h1><%= current_user.name %></h1>

<span><%= link_to "view my profile", current_user %></span>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
  <h1>About</h1>
  <p>
     This is the about page. Salathe group ftw. srsly.
  </p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact Us') %>
  <h1>Contact Us</h1>
  <p>
     This is the contact page. we live <a href="http://salathegroup.com">here</a>.
  </p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
  <h1>Help</h1>
  <p>
     This is the help page.
  </p>

app/views/static_pages/home.html.erb
<% if signed_in? %>
  <div class="row-fluid">
    <aside class="span6">

        <%= render 'shared/interaction_trunk' %>

    </aside>
  </div>  
<% else %>
	<div class="center hero-unit">
	  <h1>Welcome to my Flu App</h1>

	  <h2>
	    This is the home page, NOW SIGN UP!
	  </h2>

	  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
	</div>

<% end %> 

app/views/surveys/_answer_fields.html.erb
<fieldset>
  <%= f.label :content, "Answer" %>
  <%= f.text_field :content %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</fieldset>

app/views/symptom_sets/_form.html.erb
<%= simple_form_for @symptom_set, :html => { :class => 'form-inline' } do |f| %>
  
	<%= f.fields_for :symptoms do |builder| %>
		<%= render 'symptom_fields', f: builder %>
	<% end %>
    <p><%= link_to_add_fields "New Symptom", f, :symptoms %></p>
	
	<div class="actions"><%= f.submit %></div>
<% end %>

app/views/symptom_sets/_symptom_fields.html.erb
<fieldset>
  <%= f.input :name, 
              :collection=> ["Cough", "Fever", "Headache", "Lethargy"], 
              label: "Symptom", 
              prompt: "Select a symptom",
              :input_html => { :class => "span3" }%>  
  <%= f.hidden_field :_destroy %>

  <%= f.input :duration, 
              :collection => 1..14, 
              label: "Duration",
              prompt: "How many days?" %>
  <%= f.hidden_field :_destroy %>
</fieldset>

app/views/symptom_sets/edit.html.erb
<% title "Edit Symptom Set" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @symptom_set %> |
  <%= link_to "View All", symptom_sets_path %>
</p>

app/views/symptom_sets/index.html.erb
<% title "Symptom Sets" %>

<table>
  <tr>
    <th>User</th>
  </tr>
  <% for symptom_set in @symptom_sets %>
    <tr>
      <td><%= symptom_set.user_id %></td>
      <td><%= link_to "Show", symptom_set %></td>
      <td><%= link_to "Edit", edit_symptom_set_path(symptom_set) %></td>
      <td><%= link_to "Destroy", symptom_set, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Symptom Set", new_symptom_set_path %></p>

app/views/symptom_sets/new.html.erb
<% title "New Symptom Set" %>

<%= render 'form' %>

<p><%= link_to "Back to List", symptom_sets_path %></p>

app/views/symptom_sets/show.html.erb
<% title "Symptom Set" %>

<p>
  <strong>User:</strong>
  <%= @symptom_set.user_id %>
</p>

<p>
  <%= link_to "Edit", edit_symptom_set_path(@symptom_set) %> |
  <%= link_to "Destroy", @symptom_set, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", symptom_sets_path %>
</p>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %> 
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |form| %>
      <%= render 'shared/error_messages', object: form.object %>

      <%= form.label :name %>
      <%= form.text_field :name %>

      <%= form.label :email %>
      <%= form.text_field :email %>

      <%= form.label :password %>
      <%= form.password_field :password %>

      <%= form.label :password_confirmation, "Confirm Password" %>
      <%= form.password_field :password_confirmation %>

      <%= form.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user %>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span5 offset4">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>


      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span5">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  
  <div class="span8">
    <% if @user.symptom_sets.any? %>
      <h3>You have submitted <%= @user.symptom_sets.count %> Symptom Sets</h3>
    <% end %>
  </div>

</div>